openapi: 3.0.0
info:
  description: API documentation for AccountYou
  version: 1.0.0
  title: API Docs
servers:
  - url: 'http://localhost:3000/v1'
paths:
  /users:
    post:
      summary: Creates a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    username:
                      type: string
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    nextBillingDate:
                      type: string
                      format: date
                    isActive:
                      type: boolean
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: Created
  /categories:
    post:
      summary: Creates a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: object
                  properties:
                    userId:
                      type: string
                    name:
                      type: string
                    categoryType:
                      type: string
              required:
                - userId
                - name
                - categoryType
      responses:
        '201':
          description: Created
  /transactions:
    post:
      summary: Creates a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction:
                  type: object
                  properties:
                    userId:
                      type: string
                    categoryId:
                      type: string
                      format: email
                    transactionType:
                      type: string
                    recurring:
                      type: boolean
                    recurringPeriod:
                      type: string
                      format: date
                    amount:
                      type: number
                      format: float
                    description:
                      type: string
                    receipts:
                      type: array
                      items:
                        type: string
                    date:
                      type: string
                      format: date
              required:
                - userId
                - categoryId
                - transactionType
                - amount
                - date
      responses:
        '201':
          description: Created
