openapi: 3.0.0
info:
  description: API documentation for AccountYou
  version: 1.0.0
  title: API Docs
servers:
  - url: /api/v1
components:
  securitySchemes:
    JWTAuth: 
      type: apiKey
      in: header
      name: Authorization   
security:
  - JWTAuth: []

paths:
  /login:
    $ref: './paths/login.yaml'
  /users:
    $ref: './paths/users.yaml'
  /categories:
      $ref: './paths/categories.yaml'
  /transactions:
    post:
      summary: Creates a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/transaction.yaml'
      responses: 
        '201':
          description: Created
   