openapi: 3.0.0
info:
  description: API documentation for AccountYou
  version: 1.0.0
  title: API Docs
servers:
  - url: /api/v1
components:
  securitySchemes:
    JWTAuth: 
      type: apiKey
      in: header
      name: Authorization   
security:
  - JWTAuth: []

paths:
  /login:
    $ref: './paths/login.yaml'
  /users:
    $ref: './paths/users.yaml'
  /users/{id}:
    $ref: './paths/user.yaml'  
  /disbursements:
      $ref: './paths/disbursements.yaml'
  /dues:
      $ref: './paths/dues.yaml'
  /dues/total-dues-paid:
    $ref: './paths/total-dues-paid.yaml'
    
   